ktor:
  application:
    modules:
      - ul.group14.ApplicationKt.module
  deployment:
    port: 8080

mongoDb:
  user: app
  password: J2oH0G8hWgSSav8n
  host: musicpiracyprotectioncl.wtaaadi.mongodb.net
  maxPoolSize: 20
  databaseName: test
  clusterName: MusicPiracyProtectionCluster